spring:
  mqtt:
    username: admin
    password: public
    host-url: tcp://192.168.2.244:1883
#    client-id: zhjsbackground${random.value}
#    client-id: zzrdark1
    client-id: zzrdark2
#    client-id: zzrdark
#    default-topic: brokers/1
#    default-topic: brokers/2
    default-topic: brokers/#
#    default-topic: $SYS/brokers/+/clients/#
    # default-topic: hello
    completionTimeout: 3000
    keepAlive: 60

server:
  port: 8081