#MQTT配置信息
#MQTT-用户名
spring:
  mqtt:
    username: admin
    password: public
    host-url: tcp://192.168.2.244:1883
#    client-id: zhjsbackground${random.value}
    client-id: zzrdark
    # default-topic: $SYS/brokers/+/clients/#
    default-topic: hello
    completionTimeout: 3000
    keepAlive: 60

server:
  port: 8081